In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
x = np.ones((5,5,5))

In [3]:
print("ndim:", x.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", x.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 3
shape: (5, 5, 5)


## 1.2. Векторы. Основные понятия

### Задание 1.2.1
Введите значение получившегося нового признака share_living_space. Используйте код и ссылки на документацию из описания квартиры.
Ответ округлите до 2-х знаков после точки.

In [4]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)

round(apartment[-1],2)

0.53

### Задание 1.2.2
Укажите размерность конечного массива apartment после преобразования (ввода новой переменной и удаления старых).
Ответ является целым числом

In [5]:
len(apartment)

5

### Задание 1.2.3
Пусть дан вектор в python вида 
```python
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
```
 содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. Cчитаем, что в январе $t_0$, то есть отсчет индексов с нуля.


Выберите неверное утверждение:

 - $t_5 = 28˚C$ средняя температура воздуха в июне  

 - Минимальная средняя температура воздуха в Риме достигается в январе  

 - $t_2 = 17˚C$  средняя температура воздуха в феврале   
 

- Максимальная средняя температура воздуха в Риме достигается в июле

In [21]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
(t[5] == 28,
np.min(t) == t[0],
t[1] == 17,
np.max(t) == t[6])

(True, True, False, True)

## 1.3. Базовые операции над векторами

### Задание 1.3.3
Доходы Алексея за три месяца составили 120, 150  и 90 тысяч рублей, его жены:130 ,130  и 130 тысяч рублей, а тёщи: 2, 3 и 2.5 тысячи евро.

Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.

In [8]:
np.array([ 2, 3 ,2.5]) * 72

array([144., 216., 180.])

Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам.

In [9]:
np.array([120, 150 , 90]) + np.array([130 ,130 , 130]) + np.array([ 2, 3 ,2.5]) * 72

array([394., 496., 400.])

## 1.4. Линейная комбинация векторов

### Задание 1.4.1
Найдите линейную комбинацию векторов   $$\vec{x}=\begin{pmatrix}4\\ 5\\ \end{pmatrix}, \vec{y}=\begin{pmatrix}2\\ 1\\ \end{pmatrix}, \vec{u}=\begin{pmatrix}1\\ 0\\ \end{pmatrix}$$

с коэффициентами 2, -3 и 5

In [10]:
2*np.array([4,5]) + -3*np.array([2,1]) + 5*np.array([1,0])

array([7, 7])

### Задание 1.4.2
Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

На изготовление одной ракеты он тратит 200 рублей, а продаёт их по 400 рублей за штуку.

Найдите вектор прибыли Вовочки за эти 4 недели.

Введите координаты полученного вектора через запятую (без пробела):

In [11]:
400*np.array([1, 5, 3 , 6]) - 200*np.array([3, 4, 5 , 9])

array([-200, 1200,  200,  600])

## 1.5. Скалярное произведение векторов

### Задание 1.5.4
Вычислите длину вектора . $$\vec{x}=\begin{pmatrix}4\\ 6\\ 1\\\end{pmatrix}$$

Ответ округлите до сотых.

In [14]:
round(np.sqrt(np.dot(np.array([4,6,1]),np.array([4,6,1]))),2)

7.28

## Задание 1.5.5
Какие пары векторов являются ортогональными?  
$\vec{x}=\begin{pmatrix}4\\ 2\\ -1\\\end{pmatrix}, \vec{y}=\begin{pmatrix}2\\ 0\\ 1\\\end{pmatrix}$  
$\vec{x}=\begin{pmatrix}4\\ 5\\ -1\\\end{pmatrix}, \vec{y}=\begin{pmatrix}0\\ 0\\ 0\\\end{pmatrix}$  
$\vec{x}=\begin{pmatrix}4\\ -1\\\end{pmatrix}, \vec{y}=\begin{pmatrix}-1\\ 4\\\end{pmatrix}$  
$\vec{x}=\begin{pmatrix}4\\ -1\\\end{pmatrix}, \vec{y}=\begin{pmatrix}1\\ 4\\\end{pmatrix}$



In [26]:
(
    np.dot(np.array([4,2,-1]),np.array([2,0,1])),
    np.dot(np.array([4,5,-1]),np.array([0,0,0])),
    np.dot(np.array([4,-1]),np.array([-1,4])),
    np.dot(np.array([4,-1]),np.array([1,4]))
)

(7, 0, -8, 0)

## 1.7. --> Практика. Векторы

### Задача 1. Условие
В Hut_Paradise_DF представлен фрагмент базы данных агенства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

```python
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
```
Выполните задания 1.7.1 – 1.7.7 к Задаче 1 на Python и введите ответы в соответствующие поля ниже:

In [15]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

#### Задание 1.7.1
Найдите вектор параметров квартиры номер 5:

In [18]:
Hut_Paradise_DF.values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

#### Задание 1.7.2
Найдите вектор этажей всех квартир:

In [20]:
Hut_Paradise_DF['4.Floor'].values

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

#### Задание 1.7.3
На каком этаже расположена квартира номер 3?

In [22]:
Hut_Paradise_DF['4.Floor'].values[3]

3

#### Задание 1.7.4
Найдите количество квартир:

In [25]:
len(Hut_Paradise_DF)

9

#### Задание 1.7.5
Вычислите вектор нежилой площади:

In [26]:
(Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area']).values

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

#### Задание 1.7.6
Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны:

In [39]:
ex_rate = 4/10
(Hut_Paradise_DF['1.Rent'].values * ex_rate).astype(int)

array([3, 1, 2, 4, 8, 4, 2, 0, 4])

#### Задание 1.7.7
Пусть в 
первой квартире один просмотр занимает 10 минут,  
во второй — 20 минут,  
в третьей — полчаса,  
в четверой — 15 минут,  
в пятой — 5 минут,  
в шестой — 40 минут,  
в седьмой — 20 минут,  
в восьмой — 8 минут  
и в девятой — 20 минут.  
Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

In [48]:
demo_time = np.array([10,20,30,15,5,40,20,8,20])
demo_time

array([10, 20, 30, 15,  5, 40, 20,  8, 20])

In [50]:
((Hut_Paradise_DF['5.Demo two weeks'].values) * demo_time).sum()

1348

In [49]:
demo_time@Hut_Paradise_DF['5.Demo two weeks'].values

1348

### Задача 2. Условие
Даны три вектора:

```python
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
```
Проверьте, являются ли векторы попарно ортогональными.

Выполните задания 1.7.8 – 1.7.10 к Задаче 2 на Python и введите ответы в соответствующие поля ниже:

In [27]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

#### Задание 1.7.8
Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

In [51]:
2*v - 3*w

array([-3, 14,  3,  4,  2])

#### Задание 1.7.9
Будет ли эта комбинация ортогональна вектору u ?

In [28]:
(2*v - 3*w) @ u == 0

True

#### Задание 1.7.10
Нормируйте векторы u,v, w.

В ответ запишите, округлив до трёх знаков после точки
 - третью координату u_norm 
 - четвертую координату v_norm
 - первую координату w_norm

In [57]:
u_norm = u/np.linalg.norm(u)
v_norm = v/np.linalg.norm(v)
w_norm = w/np.linalg.norm(w)
round(u_norm[2],3), round(v_norm[3],3), round(w_norm[0],3)

(0.289, 0.667, 0.213)

## 1.8. Матрицы. Основные понятия

## 1.9. Базовые действия над матрицами

## 1.10. --> Практика. Базовые действия над матрицами
Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы NumPy

In [58]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

### Задание 1.10.1
Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.

В ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую (без пробела):

In [67]:
Inc = np.array([Husband_Income, 
Wife_Income,
Mother_In_Law_Income]).T
Inc.diagonal()

array([100, 200, 100])

### Задание 1.10.2
Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

In [68]:
Cons = np.array([Husband_Сonsumption,
Wife_Сonsumption,
Mother_In_Law_Сonsumption]).T
Cons.diagonal()

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

### Задание 1.10.3
Доходы представлены до уплаты налогов. Налоговая ставка - 13%. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте матрицу Inc из предыдущего вопроса, где расходы расположены по столбцам. В ответ запишите элементы из 1 строки этой матрицы через запятую (без пробела):

In [70]:
0.87*Inc[0]

array([ 87. , 130.5,  78.3])

### Задание 1.10.4
Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами)

В ответ запишите элементы из 3 строки этой матрицы через запятую (без пробела):

In [72]:
P = 0.87*Inc - Cons
P[2]

array([ 61.8, -26.9, -53. ])

## 1.14. Умножение и транспонирование матриц

### Задание 1.14.2
Найдите матрицу Грама G системы векторов $\vec{a}=\begin{pmatrix}1\\ 1\\\end{pmatrix}, \vec{b}=\begin{pmatrix}2\\-1\\\end{pmatrix} , \vec{c}=\begin{pmatrix}1\\ 2\\\end{pmatrix}$  



In [18]:
a, b, c = np.array([1,1]), np.array([2,-1]), np.array([1,2])
M = np.array([a,b,c])
M

array([[ 1,  1],
       [ 2, -1],
       [ 1,  2]])

In [20]:
G = np.dot(M,M.T)
G

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

## 1.15. --> Практика. Умножение матриц
### Задача 1. Условие
Даны матрица A и вектор x

In [73]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

#### Задание 1.15.1
Найдите произведение матрицы  и вектора  в том порядке, в котором их можно умножить.

Координаты вектора введите через запятую (без пробела):

In [74]:
A@x

array([26, 30])

### Задача 2. Условие
Даны две матрицы:

In [75]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

#### Задание 1.15.2
Найдите произведение матриц  и  в том порядке, в котором их можно умножить.

В ответ запишите элемент из 1 строки и 4 столбца

In [78]:
(B@A)[0,3]

14

### Задача 3. Условие
Дана система векторов: x,y,z

In [80]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

#### Задание 1.15.3
Найдите матрицу Грама системы векторов 
Введите все элементы этой матрицы через запятую (без пробела), перечисляя построчно:

In [84]:
np.array([x,y,z]) @ np.array([x,y,z]).T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

### Задача 4. Условие
В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [85]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [87]:
display(Count_DF)
display(Price_DF)

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

#### Задание 1.15.4
Найдите вектор выручки Бориса.

Введите координаты вектора через запятую (без пробела):

In [89]:
(Count_DF*Price_DF).values[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

#### Задание 1.15.5
Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

Вектор комиссий 
```python
com = [0.2, 0.2, 0.3, 0.1, 0.1]
```
Введите координаты вектора через запятую (без пробела):

In [91]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [92]:
(Count_DF*Price_DF).values @ com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

#### Задание 1.15.6
Найдите вектор прибыли стилистов.

Введите координаты вектора через запятую (без пробела):

In [98]:
(Count_DF*Price_DF).values @ (np.ones(5) - com) 

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

## 1.17. Определитель матрицы

## 1.18. Линейная (не)зависимость ч.1

## 1.19. Линейная (не)зависимость ч.2

## 1.20. --> Практика. Обратная матрица, ранг, определитель

### Задача 1. Условие
Дана матрица А

In [99]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

#### Задание 1.20.1
Найдите обратную матрицу к матрице А.

В ответ запишите элемент из 2 строки и 1 столбца, округлив его до трёх знаков после запятой

In [101]:
np.linalg.inv(A)[1,0]

0.375

### Задача 2. Условие

In [105]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

#### Задание 1.20.2
Найдите ранг системы векторов v1, v2, v3, v4.

In [120]:
M = np.array([v1,v2,v3,v4]).T

In [121]:
np.linalg.matrix_rank(M)

4

#### Задание 1.20.4
Найдите матрицу Грама системы векторов v1, v2, v3, v4.

В ответ запишите элемент из 1 строки и 4 столбца

In [124]:
(M.T @ M)[0,3]

-35

#### Задание 1.20.5
Найдите определитель матрицы Грама системы v1, v2, v3, v4.

Ответ округлите до целой части:

In [129]:
G = (M.T @ M)
round(np.linalg.det(G))

3716648.0

#### Задание 1.20.7
Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4.

В ответ запишите элемент из 3 строки и 1 столбца, округлив его до трёх знаков после запятой

In [131]:
round(np.linalg.inv(G)[2,0],3)

-0.026