In [8]:
import pandas as pd
import numpy as np
import math

In [2]:
np.array([14.3, 21.2, 8.34, 15.32]) + np.array([4.3, 3.1, 0.36, 12.42])

array([18.6 , 24.3 ,  8.7 , 27.74])

In [ ]:
np.array([18.6, 24.3, 8.7, 27.74])

In [66]:
def sq(x:int):#-> float:
    return x**2

sq(2.5)

6.25

Задание 24
Решается задача бинарной классификации: заданы факторы ,  и  и целевая переменная , которая принимает значение двух классов —  и .

В качестве модели классификации используется логистическая регрессия. После обучения модели были найдены её веса:

С помощью построенной модели найдите оценку вероятности принадлежности к классу 1, если вектор признаков для нового объекта имеет вид .

In [11]:
w_0,w_1, w_2,w_3 = -9, 0.04, 0.09, 0.03


x_1,x_2 ,x_3 = 180, 51, 39
z = w_0 + w_1*x_1 + w_2*x_2 + w_3*x_3
p = 1/(1+math.exp(-z))
p

0.9812934900456455

In [27]:
x = np.array([-2,-1,0,1,2])
p = np.array([0.05,0.63,0.2,0.07,0.05])
(x*p).sum()
x**2# * p
(x**2 * p).sum() - ((x*p).sum())**2

0.7864000000000002

In [28]:
1.1 - 0.56**2

0.7864

In [18]:
sum([0.2,0.07,0.05])
sum([-0.1 , -0.63,  0.  ,  0.07,  0.  ])

-0.6599999999999999

In [32]:
a = np.array([[2,-6],[-6,18]])
a

array([[ 2, -6],
       [-6, 18]])

In [31]:
np.linalg.det(a)

-1.9984014443252774e-15

In [35]:
np.array([5, 10, 21, 15, 24]) - np.array([5, 10, 21, 15, 24]).mean()

array([-10.,  -5.,   6.,   0.,   9.])

In [ ]:
37/50

In [38]:
-37/50*(25/37*np.log2(25/37) + 12/37*np.log2(12/37))

0.672676395504983

In [39]:
37/37*np.log2(37/37) + 0/37*np.log2(12/37)

0.0

In [40]:
x = np.array([1,3,5])
y = np.array([2.1,2.9,4.1])

In [46]:
w0 = 0.35
w1 = 2.19

y_ = w0 + w1*x
((y_-y)**2).sum()

68.19399999999999

In [47]:
w0 = 1.53
w1 = 0.5

y_ = w0 + w1*x
((y_-y)**2).sum()

0.02669999999999998

In [48]:
w0 = 0.5
w1 = 1.53

y_ = w0 + w1*x
((y_-y)**2).sum()

21.203500000000005

In [49]:
w0 = 2.19
w1 = 0.35

y_ = w0 + w1*x
((y_-y)**2).sum()

0.33479999999999976