In [123]:
import numpy as np
import pandas as pd

#### Задание 2.5
Ниже представлены доходы семьи за три месяца.
```
Доходы мужа: 120, 150 и 190 тысяч рублей.
Доходы жены: 130, 130 и 130 тысяч рублей.
Доходы тёщи: 2, 3 и 2.5 тысячи евро.
```
Вводите координаты полученных векторов через запятую (без пробела). Пример ввода ответа: 0,1,1.

Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.

In [2]:
euro = 72
mother_in_law_income = np.array([2,3,2.5])
mother_in_law_income*euro

array([144., 216., 180.])

Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам.

In [3]:
husband_incom = np.array([120,150,190])
wife_income = np.array([130,130,130])
husband_incom + wife_income + mother_in_law_income*euro

array([394., 496., 500.])

#### Задание 2.7
Найдите линейную комбинацию векторов $\overrightarrow{x}=\left( \begin{array}{c}
4 \\ 
5 \end{array}
\right),\ \overrightarrow{y}=\left( \begin{array}{c}
2 \\ 
1 \end{array}
\right)\ ,\ \overrightarrow{u}=\left( \begin{array}{c}
1 \\ 
0 \end{array}
\right)$ с коэффициентами 2, -3 и 5 соответственно.

Пример ввода ответа (через запятую, без пробелов): 0,1.

In [4]:
x, y, u = np.array([4,5]), np.array([2,1]), np.array([1,0])
2*x - 3*y + 5*u

array([7, 7])

#### Задание 2.8
Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.

На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.

Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.

В качестве ответа введите координаты вектора через запятую, без пробелов. Пример ввода ответа: 0,1,1,1.

In [5]:
cost, revenue = np.array([3,4,5,9]), np.array([1,5,3,6])
400*revenue - 200*cost


array([-200, 1200,  200,  600])

В Hut_Paradise_DF представлен фрагмент базы данных агентства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [7]:


Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [9]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

#### Задание 3.3
Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

`Hut_Paradise_values = Hut_Paradise_DF.values`
  

In [10]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

#### Задание 3.4
Найдите вектор этажей всех квартир

In [11]:
Hut_Paradise_values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

#### Задание 3.5
Вычислите вектор нежилой площади. Выберите координаты полученного вектора:

In [12]:
Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

#### Задание 3.6
Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [14]:
show_time = np.array([10,20,30,15,5,40,20,8,20])
total_time = show_time@Hut_Paradise_values[:,4]
total_time

1348

Дано три вектора:

In [15]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов $v$ и $w$ с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [17]:
2*v - 3*w

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору $u$?

In [18]:
(2*v - 3*w)@u

0

Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

```import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])
```


In [21]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])



#### Задание 5.1
Составьте матрицу $Inc$ доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [29]:
Inc = np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
print(*Inc.diagonal(),sep=',')

100,200,100


#### Задание 5.2
Составьте матрицу $Cons$ расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [33]:
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
print(*Cons.diagonal(),sep=',')

50,80,140


#### Задание 5.3
Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу $Inc$ , где доходы расположены по столбцам.

Выберите список элементов из первой строки этой матрицы (строки нумеруются с 1):

In [35]:
Inc_aft_tax = (1-0.13)*Inc
Inc_aft_tax[0]

array([ 87. , 130.5,  78.3])

#### Задание 5.4
Вычислите матрицу $P$, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

Выберите список элементов из третьей строки этой матрицы:

In [38]:
P = Inc_aft_tax - Cons
P[2]

array([ 61.8, -26.9, -53. ])

#### Задание 6.3
В произведении  $C = A \cdot B$ матриц   
$A=\left( \begin{array}{ccccc}
1 & -1 & 2 & 4 & 0 \\ 
8 & 2 & 0 & 5 & 3 \\ 
0 & 1 & 2 & 1 & 2 \end{array}
\right)$ и $B=\left( \begin{array}{cccc}
1 & 0 & 1 & 0 \\ 
0 & 0 & 2 & -1 \\ 
1 & 0 & 1 & 1 \\ 
0 & 1 & 1 & 1 \\ 
1 & 1 & 0 & -1 \end{array}
\right)$   
найдите элементы: $C_{12} =$ , $C_{34} =$




In [57]:
A = np.array([[1 , -1 , 2 , 4 , 0],
              [8 , 2, 0 , 5 , 3 ],
              [0 , 1 , 2 , 1, 2]])
B = np.array([[1 , 0 , 1 , 0],
              [0 , 0 , 2 , -1],
              [1 , 0 , 1 , 1 ],
              [0 , 1 , 1 , 1],
              [1 , 1 , 0 , -1]])

AB = (A@B)
AB[0,1], AB[2,3]

(4, 0)

#### Задание 6.5
Найдите тензорное произведение векторов $\overrightarrow{a}=\left( \begin{array}{c}
1 \\ 
3 \end{array}
\right)$ и $\overrightarrow{b}=\left( \begin{array}{c}
-3 \\ 
1 \end{array}
\right)$ .

Заполните текстовые поля слева направо, сверху вниз:
$\overrightarrow{a}\bigotimes \overrightarrow{b}=$

In [78]:
a, b  = np.array([1,3],ndmin=2), np.array([-3,1],ndmin=2)
(a.T)@b

array([[-3,  1],
       [-9,  3]])

#### Задание 6.9
Составьте матрицу $A$ из системы векторов: $ \overrightarrow{a}=\left( \begin{array}{c}
1 \\ 
1 \end{array}
\right),\ \overrightarrow{b}=\left( \begin{array}{c}
2 \\ 
-1 \end{array}
\right)\ \ ,\overrightarrow{c}=\left( \begin{array}{c}
1 \\ 
2 \end{array}
\right)\$ .


 
Найдите матрицу Грама $ G=A^T\cdot A$.

Выберите верный вариант ответа:

In [83]:
a, b, c = np.array([1,1]), np.array([2,-1]), np.array([1,2])

A = np.array([a,b,c]).T
A, (A.T)@A

(array([[ 1,  2,  1],
        [ 1, -1,  2]]),
 array([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]]))

#### Задание 7.1
Даны матрица $A$ и вектор 
$\vec{х}$
:
```python
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
```
Найдите произведение матрицы  $A$ и вектора $\vec{х}$ в том порядке, в котором их можно умножить.

В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. 

In [85]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
print(*A@x,sep=',')

26,30


#### Задание 7.2
Даны две матрицы:
```python
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
```
Найдите произведение матриц $A$ и $B$ в том порядке, в котором их можно умножить.

В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [90]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
(B@A)[0,3]

14

#### Задание 7.3
Дана система векторов:
```python
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
```
Составьте матрицу $A$, расположив векторы $\vec{x}$, $\vec{y}$, $\vec{z}$ в строках. Найдите матрицу Грама $G$  системы векторов $\vec{x}$, $\vec{y}$, $\vec{z}$.

Чему равна полученная матрица Грама ?

In [93]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([x,y,z])
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

### УСЛОВИЕ ДЛЯ ЗАДАНИЙ 7.4 И 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

 - В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
 - В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.
 
```python
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
```

In [96]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

#### Задание 7.4
Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

Вектор комиссий: `com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])`.

Выберите координаты вектора прибыли салона:

In [111]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [118]:
(Count_DF.values * Price_DF.values)@com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

#### Задание 7.5
Найдите вектор прибыли стилистов.


In [119]:
after_com = np.ones(len(com)) - com
(Count_DF.values * Price_DF.values)@after_com

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [122]:
A = np.matrix ("1, 2, 3; 4  5  6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-2.9999999999999982


#### Задание 10.1
Дана матрица $A$:

`A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])`
Найдите матрицу, обратную матрице .

В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.

In [129]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
round(np.linalg.inv(A)[1,0],3)

0.375

###УСЛОВИЕ ДЛЯ ЗАДАНИЙ 10.2-10.7

Дана система векторов:

```python
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
```

In [130]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

#### Задание 10.2
Найдите ранг системы векторов $\vec(v1), \vec(v2), \vec(v3), \vec(v4)$. Для этого создайте матрицу системы векторов. Векторы в матрице расположите **в столбцы**.

In [134]:
A = np.array([v1,v2,v3,v4]).T
np.linalg.matrix_rank(A) 

4

#### Задание 10.4
Найдите матрицу Грама системы векторов $\vec(v1), \vec(v2), \vec(v3), \vec(v4)$ : $G={\mathrm{A}}^{T}A$. В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [136]:
(A.T@A)[0,3]

-35

#### Задание 10.5
Найдите определитель матрицы Грама $G$ системы $\vec(v1), \vec(v2), \vec(v3), \vec(v4)$ . Ответ округлите до целого числа.

In [139]:
round(np.linalg.det(A.T@A))

3716648

#### Задание 10.7
Найдите обратную матрицу к матрице Грама $G$  системы , $\vec(v1), \vec(v2), \vec(v3), \vec(v4)$ . В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [143]:
round(np.linalg.inv(A.T@A)[2,0],3)

-0.026