In [9]:
import numpy as np
import sympy

In [3]:
sympy.sqrt(12)

2*sqrt(3)

In [4]:
from sympy import FiniteSet, Union
l1 = [1, 3, 7, 10] 
l2 = [9, 7, 1] 
a = FiniteSet(*l1) 
b = FiniteSet(*l2) 
Union(a, b)

FiniteSet(1, 3, 7, 9, 10)

In [7]:
a, b = set(l1) ,set(l2) 
a|b

{1, 3, 7, 9, 10}

In [8]:
from sympy import ConditionSet, Eq, Symbol, Interval
x=Symbol('x')
s=ConditionSet(x, Eq(x**2-5*x,0), Interval(2,9))
s

ConditionSet(x, Eq(x**2 - 5*x, 0), Interval(2, 9))

In [13]:
s | {0}

Union(ConditionSet(x, Eq(x**2 - 5*x, 0), Interval(2, 9)), FiniteSet(0))

##### УСЛОВИЕ ДЛЯ ЗАДАНИЙ 2.6-2.8

Представьте, что вы являетесь куратором образовательной программы, на которой будет два вебинара: по программированию и по машинному обучению.

На вебинар по программированию записались потенциальные слушатели со следующими электронными адресами:

- bennet@xyz.com
- darcy@abc.com
- margaret@xyz.com
- pa@hhh.com
- marimari@xyz.com
- mallika@yahoo.com
- abc@xyz.com
- 0071235@gmail.ru   
На вебинар по машинному обучению записались потенциальные слушатели со следующими электронными адресами:

- marimari@xyz.com
- darcy@abc.com
- 0071235@gmail.ru
- darcy@abc.com
- petr44@xyz.com
- katrin@ya.com   
Оформите множества в Python для обоих списков слушателей.

In [17]:
prog_attendee = {'bennet@xyz.com','darcy@abc.com','margaret@xyz.com','pa@hhh.com',
 'marimari@xyz.com','mallika@yahoo.com','abc@xyz.com','0071235@gmail.ru'}

data_science_attendee = {'marimari@xyz.com','darcy@abc.com','0071235@gmail.ru','darcy@abc.com',
 'petr44@xyz.com','katrin@ya.com'}

##### Задание 2.6
С помощью операций множеств в Python определите, сколько слушателей записалось на оба вебинара.

In [19]:
len(prog_attendee & data_science_attendee)

3

#### Задание 2.7
Сколько человек заинтересованы в посещении хотя бы одного вебинара?

In [21]:
len(prog_attendee | data_science_attendee)

10

#### Задание 2.8
Сколько человек заинтересованы в посещении только одного вебинара из двух?

In [22]:
len(prog_attendee ^ data_science_attendee)

7

Мы можем вычислять область определения и с помощью библиотеки Python для символьных вычислений, с которой мы познакомились ранее — `SymP`.

Например, рассчитаем область определения для функции :$f(x) = \frac{1}{x}$

```python
from sympy import Symbol, S #импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области определения
from sympy.calculus.util import continuous_domain
x = Symbol("x") #определяем нашу переменную
f = 1/x #определяем нашу функцию
continuous_domain(f, x, S.Reals) #вычисляем область определения

```

In [24]:
from sympy import Symbol, S #импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области определения
from sympy.calculus.util import continuous_domain
x = Symbol("x") #определяем нашу переменную
f = 1/x #определяем нашу функцию
continuous_domain(f, x, S.Reals) #вычисляем область определения

Union(Interval.open(-oo, 0), Interval.open(0, oo))

Для функции :$f(x) = \frac{log(x)}{x}$
```python
from sympy import log
x = Symbol("x")
f = log(x)/x
continuous_domain(f, x, S.Reals)
```

In [25]:
from sympy import log
x = Symbol("x")
f = log(x)/x
continuous_domain(f, x, S.Reals)

Interval.open(0, oo)

область значений мы также можем найти с помощью библиотеки SymPy. Например, сделаем это для функции $sin(x)$:

In [30]:
from sympy.calculus.util import function_range
from sympy import sin
x = Symbol("x") 
f = sin(x) 
function_range(f, x, S.Reals)

Interval(-1, 1)

Или для более сложной функции : $f(x) = \frac{x^2 - 3}{e^x}$

In [31]:
from sympy import Symbol, S #импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области значений
from sympy import exp #добавляем функцию для вычисления экспоненциальной функции
x = Symbol("x")
f = (x*x-3)/(exp(x))
function_range(f, x, S.Reals)

Interval(-2*E, oo)

Для того чтобы найти эти точки пересечения, мы также можем использовать библиотеку SymPy. Например, найдём точки пересечения для функции:
$$f(x) = x^2 + 5x + 4$$
Сначала найдём точку пересечения с осью ординат. Для этого просто подставим 0 вместо значения $x$ :

In [32]:
x = Symbol("x")
f = x*x+5*x+4
f.subs(x, 0)


4

Теперь найдём точку пересечения с осью абсцисс. Для этого решим уравнение, в котором приравняем нашу функцию к нулю:



In [33]:
from sympy import solveset, Eq
solveset(Eq(x*x+5*x+4, 0), x)

FiniteSet(-4, -1)

Для того чтобы найти производную с помощью SymPy, необходимо лишь указать, какой буквой обозначается переменная, ввести функцию и применить метод `diff()`.

Пример № 1

Вычислить производную для функции $f(x) = x^4 +3x^3+4x^2+8$.

In [34]:
import sympy
x = sympy.Symbol("x")
expr = x**4 + 3*x**3 + 4*x**2 + 8
expr.diff(x)

4*x**3 + 9*x**2 + 8*x

In [35]:
expr.integrate(x)

x**5/5 + 3*x**4/4 + 4*x**3/3 + 8*x

Пример № 2

Вычислить производную для функции $f(x) = ln(x^2 + 5x) + e^{sin(x)}$

In [37]:
import sympy
# from sympy import diff, sin, exp, log, Symbol
x = sympy.Symbol("x")
expr = log(x**2 + 5*x) + exp(sin(x))
expr.diff(x)

(2*x + 5)/(x**2 + 5*x) + exp(sin(x))*cos(x)

#### Задание 6.5 (на самопроверку)
С помощью библиотеки SymPy найдите производную для функции $y = sin(x*3 + log(x))*exp((x))$

In [39]:
x = sympy.Symbol("x")
expr = sin(3*x + log(x))*exp(x)
# log(x**2 + 5*x) + exp(sin(x))
expr.diff(x)

(3 + 1/x)*exp(x)*cos(3*x + log(x)) + exp(x)*sin(3*x + log(x))

In [ ]:
𝑦=𝑠𝑖𝑛(𝑥∗3+𝑙𝑜𝑔(𝑥))∗𝑒𝑥𝑝((𝑥))

### УСЛОВИЕ ДЛЯ ЗАДАНИЙ 8.1-8.11

Исследуемая функция: $y = \frac{x^3}{2(x+5)^2}$.

#### Задание 8.1
Найдите область определения функции:

In [40]:
from sympy import Symbol, S
from sympy.calculus.util import continuous_domain 
x = Symbol("x") 
f = (x**3)/(2*(x+5)**2) 
continuous_domain(f, x, S.Reals)

Union(Interval.open(-oo, -5), Interval.open(-5, oo))

#### Задание 8.2
Найдите область значений функции:

In [41]:
function_range(f, x, S.Reals)

Interval(-oo, oo)

#### Задание 8.4
В какой точке график пересекает ось абсцисс? В качестве ответа введите координату по х.

In [43]:
from sympy import solveset, Eq
solveset(Eq(f, 0), x)

FiniteSet(0)

#### Задание 8.5
В какой точке график пересекает ось ординат? В качестве ответа введите координату по y.

In [44]:
f.subs(x, 0)

0

#### Задание 8.6
Найдите производную от функции:

In [45]:
ff = f.diff(x)

-x**3/(x + 5)**3 + 3*x**2/(2*(x + 5)**2)

#### Задание 8.7
Найдите точку максимума. Если её нет, введите в качестве ответа слово нет.

In [46]:
ff = f.diff(x)

In [48]:
solveset(Eq(ff, 0), x)

FiniteSet(-15, 0)

In [53]:
ff.subs(x, -16),ff.subs(x, -14),ff.subs(x, -4),ff.subs(x,14)

(128/1331, -98/729, 88, 2842/6859)

#### Задание 8.10
Вычислите вторую производную функции:

In [54]:
ff.diff(x)

3*x**3/(x + 5)**4 - 6*x**2/(x + 5)**3 + 3*x/(x + 5)**2

#### Задание 8.11
На каком(-их) интервале(-ах) функция выпукла вверх?

In [55]:
fff = ff.diff(x)
solveset(Eq(fff, 0), x)

FiniteSet(0)

In [56]:
fff.subs(x, -6),fff.subs(x, -4),fff.subs(x, 1)

(-450, -300, 25/432)

#### Задание 9.3
На каком(-их) интервале(-ах) убывает функция $h(x) = -x^3 + 3x^2 + 9$?

In [58]:
from sympy import Symbol, S
from sympy.calculus.util import continuous_domain 
x = Symbol("x") 
h = -x**3 +3*x**2 +9

In [59]:
h.diff(x)

-3*x**2 + 6*x

#### Задание 1.7
Пусть у нас есть реальные и предсказанные значения в некоторой прогностической модели:

Реальные	6	7	6	4	5	6	8    
Предсказанные	6.4	7.1	5.9	4.2	5.2	6.2	7.5    

Найдите значение метрики $L^2$-loss:


In [71]:
y_true = np.array([6,7,6,4,5,6,8])
y_pred = np.array([6.4,7.1,5.9,4.2,5.2,6.2,7.5])

((y_true - y_pred)**2).sum()

0.5500000000000004

In [96]:
from sympy import *
 
x, y = symbols('x, y')
eq1 = Eq(3*x**2+3*y**2-15,0)
eq2 = Eq(6*x*y-12, 0)
 
sol = solve([eq1, eq2], [x, y])

sol

[(-2, -1), (-1, -2), (1, 2), (2, 1)]

$Hesse = \begin{pmatrix} 6x & 6y\\ 6y & 6x\\ \end{pmatrix}$

In [97]:
x,y = (-2, -1)
H = np.array([[6*x,6*y],[6*y,6*x]])
H

array([[-12,  -6],
       [ -6, -12]])

In [12]:
x,y = (-1, -2)
H = np.array([[6*x,6*y],[6*y,6*x]])
H

array([[ -6, -12],
       [-12,  -6]])

In [13]:
x,y = (1, 2)
H = np.array([[6*x,6*y],[6*y,6*x]])
H

array([[ 6, 12],
       [12,  6]])

In [14]:
x,y = (2, 1)
H = np.array([[6*x,6*y],[6*y,6*x]])
H

array([[12,  6],
       [ 6, 12]])

Задание 3.4
Найдите экстремумы функции $z = 4x^2 - 6xy -34x + 5y^2 + 42y + 7$.


In [24]:
from sympy import *
 
x, y = symbols('x, y')

z = 4*x**2 - 6*x*y - 34*x + 5*y**2 +42*y +7

z_x,z_y  = z.diff(x), z.diff(y)

sol = solve([z_x, z_y], [x, y])
sol

{x: 2, y: -3}

#### Задание 3.5
Вычислите матрицу Гессе для функции $f(x,y) = x^3 - 2xy - y^6$ в точке $(1;2)m$ и найдите её определитель:

In [82]:
from sympy.matrices import Matrix
from sympy import *

In [98]:
x, y = symbols('x, y')
f = x**3 -2*x*y -y**6

H = Matrix([[f.diff(x,x),f.diff(x,y)],[f.diff(y,x),f.diff(y,y)]])
x0,y0 = 1,2 
H_0 = H.subs(x,x0).subs(y,y0)

H_0.det()

-2884

In [99]:
H_0.eigenvals()

{-sqrt(59053) - 237: 1, -237 + sqrt(59053): 1}

#### Задание 3.9
Найдите экстремумы функции $z = x^3 + y^3 - 3xy$.

Запишите координаты точки минимума:    
Запишите координаты седловой точки:

In [102]:
z = x**3 + y**3 - 3*x*y
z_x,z_y  = z.diff(x), z.diff(y)
slv = solve([z_x,z_y ],[x,y])
slv

[(0, 0),
 (1, 1),
 ((-1/2 - sqrt(3)*I/2)**2, -1/2 - sqrt(3)*I/2),
 ((-1/2 + sqrt(3)*I/2)**2, -1/2 + sqrt(3)*I/2)]

In [105]:
H = Matrix([[z.diff(x,x),z.diff(x,y)],[z.diff(y,x),z.diff(y,y)]])
x0,y0 = slv[0]
x0,y0, H.subs(x,x0).subs(y,y0).eigenvals()

(0, 0, {-3: 1, 3: 1})

In [106]:
x0,y0 = slv[1]
x0,y0, H.subs(x,x0).subs(y,y0).eigenvals()

(1, 1, {9: 1, 3: 1})