In [1]:
import numpy as np
import pandas as pd

#### Задание 1.1
Найдите скалярное произведение векторов:   
$\vec{v_{1}}  = (-1, 2, \ -7, 9)^T$   
$\vec{v_{2}}  = (2, 8, 2, \ -1)^T$





In [6]:
v1, v2 = np.array([-1,2,-7,9]), np.array([2,8,2,-1])
v1@v2

-9

#### Задание 1.4
Задана матрица

$A=\left( \begin{array}{cccc}
1 & 1 \\  
1 & 2 \end{array}
\right)$

Найдите матрицу Грама $A^{T}A$.

In [10]:
A = np.array([[1,1],[1,2]])
A.T@A

array([[2, 3],
       [3, 5]])

#### Задание 1.7
Найдите ранг матрицы системы, составленной из векторов:   
$\vec{v_{1}}  = (2, 10, \ -2)^T$   
$\vec{v_{2}}  = (3, 2, \ -2)^T$   
$\vec{v_{3}}  = (8, 14, \ -6)^T$

In [18]:
v1, v2, v3 = np.array([2,10,-2]), np.array([3,2,-2]), np.array([8,14,-6])
A = np.array([v1,v2,v3]).T
np.linalg.matrix_rank(A)

2

#### Задание 1.8
Определите линейную (не)зависимость системы векторов:   
$\vec{v_{1}}  = (2, 10, \ -2)^T$   
$\vec{v_{2}}  = (3, 2, \ -2)^T$   
$\vec{v_{3}}  = (8, 14, \ -6)^T$


In [19]:
v1, v2, v3 = np.array([2,10,-2]), np.array([3,2,-2]), np.array([8,14,-6])
A = np.array([v1,v2,v3]).T
np.linalg.matrix_rank(A)

2

#### Задание 1.10
Запишите СЛАУ в матричном виде и классифицируйте её:
![](https://lms.skillfactory.ru/assets/courseware/v1/47352a6323f8d5d16f441a40b203b76f/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md2_1_9.png)



In [23]:
v1 = np.array([5,0,10])
v2 = np.array([1,2,0])
v3 = np.array([3,8,2])
b = [1,10,0]
A = np.array([v1,v2,v3]).T

array([[ 5,  1,  3],
       [ 0,  2,  8],
       [10,  0,  2]])

##### Задание 2.4
Решите систему линейных уравнений:

![](https://lms.skillfactory.ru/assets/courseware/v1/bb410f21af5bc73df165cf79d3623d37/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md2_2_23.png)

In [29]:
A = np.array([[4,5],[7,10]]).T
b = np.array([20,30])

x,y = np.linalg.inv(A)@b
print(x,y)

-2.0 4.0


#### Задание 2.6

Сколько решений имеет представленная ниже система уравнений?

![](https://lms.skillfactory.ru/assets/courseware/v1/8682fe804f6fc58ebde2eaeee54b6a26/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md2_2_37.png)

In [38]:
A = np.array([[4,-4,0],[7,2,9],[-1,5,4]]).T
A_b = np.array([[4,-4,0],[7,2,9],[-1,5,4],[7,3,10]]).T
np.linalg.matrix_rank(A),np.linalg.matrix_rank(A_b)

(2, 2)

#### Задание 2.9
Вычислите вектор ошибок для приближённого решения системы , если:

![](https://lms.skillfactory.ru/assets/courseware/v1/e5455f82f2c719a89defd6fbf935bf99/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md2_2_61.png)

Введите координаты полученного вектора через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [41]:
A = np.array([[1,2,1],[-5,1,1]]).T
b = np.array([1,2,2])
w_ = np.array([1,1])

In [44]:
print(*(b - A@w_),sep=',')

5,-1,0


#### Задание 2.11
Найдите $OLS$-оценку для коэффициентов $w1$, $w2$ СЛАУ:

![](https://lms.skillfactory.ru/assets/courseware/v1/aabe72a5dc4493bf7f00fce4be816414/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md2_2_63.png)

Для этого выполните задания под цифрами 1-4 ниже.

1. Вычислите матрицу Грама столбцов $A:A^{T}A$=

In [48]:
A = np.array([[1,-3,1,1],[2,1,2,-1]]).T
G = A.T@A
G

array([[12,  0],
       [ 0, 10]])

2. Вычислите матрицу $G^{-1}$ =  $(A^{T}A)^{-1}$. Она имеет вид:


In [50]:
np.linalg.inv(G)

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

3. Вычислите $A^{T} \vec{b}$. Введите координаты полученного вектора через запятую, без пробелов. Пример ввода ответа: 1,1.

In [52]:
b = np.array([1,4,5,0])
print(*(A.T@b),sep=',')

-6,16


4. Вычислите вектор оценок коэффициентов $\vec{v}$ .
Примечание: для корректного ответа не округляйте .

Чему равен полученный вектор коэффициентов?

In [54]:
np.linalg.inv(G)@A.T@b

array([-0.5,  1.6])

Рассмотрим классический датасет для обучения линейной регрессии — Boston Housing. В нём собраны усреднённые данные по стоимости недвижимости в 506 районах Бостона. Ниже вы видите фрагмент датасета.

Целевой переменной будет PRICE — это, в некотором смысле, типичная (медианная) стоимость дома в районе.

Для примера возьмём в качестве регрессоров уровень преступности (CRIM) и среднее количество комнат в доме (RM).

In [55]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from sklearn import datasets # для импорта данных
import seaborn as sns # для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

# загружаем датасет
boston = datasets.load_boston()
boston_data = pd.DataFrame(
    data=boston.data, #данные
    columns=boston.feature_names #наименования столбцов
)
boston_data['PRICE'] = boston.target
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [56]:
# составляем матрицу А и вектор целевой переменной
CRIM = boston_data['CRIM']
RM = boston_data['RM']
A = np.column_stack((np.ones(506), CRIM, RM))
y = boston_data[['PRICE']]
print(A)

[[1.0000e+00 6.3200e-03 6.5750e+00]
 [1.0000e+00 2.7310e-02 6.4210e+00]
 [1.0000e+00 2.7290e-02 7.1850e+00]
 ...
 [1.0000e+00 6.0760e-02 6.9760e+00]
 [1.0000e+00 1.0959e-01 6.7940e+00]
 [1.0000e+00 4.7410e-02 6.0300e+00]]


In [57]:
# вычислим OLS-оценку для коэффициентов
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat.values)

[[-29.24471945]
 [ -0.26491325]
 [  8.39106825]]


In [58]:
# Теперь составим прогноз нашей модели:
# добавились новые данные:
CRIM_new = 0.1
RM_new = 8
# делаем прогноз типичной стоимости дома
PRICE_new = w_hat.iloc[0]+w_hat.iloc[1]*CRIM_new+w_hat.iloc[2]*RM_new
print(PRICE_new.values)

[37.85733519]


In [59]:
# короткий способ сделать прогноз
new=np.array([[1,CRIM_new,RM_new]])
print('prediction:', (new@w_hat).values)

prediction: [[37.85733519]]


Мы уже знаем, что алгоритм построения модели линейной регрессии по МНК реализован в классе LinearRegression, находящемся в модуле sklearn.linear_model. Для вычисления коэффициентов (обучения модели) нам достаточно передать в метод fit() нашу матрицу с наблюдениями и вектор целевой переменной, а для построения прогноза — вызвать метод predict():

In [60]:
from sklearn.linear_model import LinearRegression
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)
# вычисляем коэффициенты регрессии
model.fit(A, y)
print('w_hat:', model.coef_)
new_prediction = model.predict(new)
print('prediction:', new_prediction)

w_hat: [[-29.24471945  -0.26491325   8.39106825]]
prediction: [[37.85733519]]


#### Задание 3.5
Сделайте прогноз типичной стоимости (в тыс. долларов) дома в городе с уровнем преступности $CRIM = 0.2$ и средним количеством комнат в доме $RM = 6$. В качестве модели используйте линейную регрессию, оценка вектора коэффициентов которой равна:    
$$\hat{\vec{w}} = (-29.3, \ -0.26, \ 8.4)$$



In [66]:
crim, rm = 0.2, 6
w_ = np.array([[-29.3,-0.26,8.4]])
x = np.array([[1,crim, rm]])

In [73]:
pred = w_@x.T
pred.round()

array([[21.]])

#### Задание 4.3
Стандартизируйте вектор $\vec{x}=(12, 8)^T$, приведя его к единичной длине. В качестве ответа введите координаты полученного вектора. Ответ округлите до третьего знака после точки-разделителя.

In [79]:
x = np.array([12,8])
x_cent = x - x.mean()
(x_cent/np.linalg.norm(x_cent)).round(3)

array([ 0.707, -0.707])

#### Задание 4.7
Вычислите коэффициент корреляции между векторами $\vec{v}=(5, 1, 2)^T$ и $\vec{u}=(4, 2, 8)^T$.

Ответ округлите до двух знаков после точки-разделителя.

In [106]:
v, u = np.array([5,1,2]), np.array([4,2,8])
A = np.column_stack([v,u])
A_cent = A-A.mean(axis=0)
A_norm = A_cent/np.linalg.norm(A_cent,axis=0)
ans = A_norm[:,0]@A_norm[:,1]

0.05241424183609589

#### Задание 4.8
3 points possible (graded)
Составьте корреляционную матрицу для системы векторов:   
$\vec{x}_1=(5.1, 1.8, 2.1, 10.3, 12.1, 12.6)^T$   
$\vec{x}_2=(10.2, 3.7, 4.1, 20.5, 24.2, 24.1)^T$   
$\vec{x}_3=(2.5, 0.9, 1.1, 5.1, 6.1, 6.3)^T$   

Для расчёта используйте библиотеку NumPy или Pandas.

In [125]:
 x1, x2, x3 = [np.array(x) for x in 
               [[5.1,1.8,2.1,10.3,12.1,12.6],[10.2,3.7,4.1,20.5,24.2,24.1],[2.5,0.9,1.1,5.1,6.1,6.3]]]

A = np.column_stack([x1, x2, x3])

1. Чему равен ранг полученной корреляционной матрицы?

In [134]:
corr_matrix = np.corrcoef(A.T)
np.linalg.matrix_rank(corr_matrix)

3

2. Чему равен определитель полученной корреляционной матрицы? Ответ округлите до седьмого знака после точки-разделителя.

In [137]:
round(np.linalg.det(corr_matrix),7)

5e-07

### 5. Практика: линейная регрессия и метод наименьших квадратов

In [138]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline

У Василия, основателя компании «Газ-Таз-Ваз-Нефть», дела идут в гору: в этом году он открывает 100 новых скважин по добыче газа. Однако в целях оптимизации расходов и для потенциального повышения дохода Василию необходимо оценить, сколько денег будет приносить ему каждая из скважин, а также понять, какие факторы потенциально сильнейшим образом влияют на объём добычи газа. Для этого Василий решил нанять вас как специалиста по построению моделей машинного обучения.

Василий представляет вам набор данных о добыче газа на своих скважинах.
Признаки:

- Well — идентификатор скважины;
- Por — пористость скважины (%);
- Perm — проницаемость скважины;
- AI — акустический импеданс $(кг/м^2 * 10^6$);
- Brittle — коэффициент хрупкости скважины (%);
- TOC — общий органический углерод (%);
- VR — коэффициент отражения витринита (%);
- Prod — добыча газа в сутки (млн. кубических футов).

Ваша задача — построить регрессионную модель, которая прогнозирует выработку газа на скважине (целевой признак — Prod) на основе остальных характеристик скважины, и проинтерпретировать результаты вашей модели.

In [140]:
data = pd.read_csv('./Unit_5_data/unconv.csv') 
data.head()

Well    Por  Perm    AI  Brittle   TOC    VR         Prod
0     1  12.08  2.92  2.80    81.40  1.16  2.31  4165.196191
1     2  12.38  3.53  3.22    46.17  0.89  1.88  3561.146205
2     3  14.02  2.59  4.01    72.80  0.89  2.72  4284.348574
3     4  17.67  6.75  2.63    39.81  1.08  1.88  5098.680869
4     5  17.52  4.57  3.18    10.94  1.51  1.90  3406.132832

Для начала в качестве модели будем использовать простую линейную регрессию.    
    
    
    
#### Задание 5.1
Постройте корреляционную матрицу факторов, включив в неё целевой признак. Ответьте на следующие вопросы:

1. Выберите топ-3 факторов, наиболее коррелированных с целевой переменной:

In [156]:
cor_matrix = data.corr()
print(*cor_matrix.Prod.abs().sort_values(ascending=False).index[1:4])

Por Perm TOC


2. Вычислите ранг полученной матрицы корреляций:

In [157]:
np.linalg.matrix_rank(cor_matrix.values)

8

3. Вычислите определитель матрицы корреляций. Ответ округлите до четвёртого знака после точки-разделителя.

In [159]:
round(np.linalg.det(cor_matrix.values),4)

0.0007

#### Задание 5.2
Создайте матрицу наблюдений. Обозначьте её за $X$, а вектор правильных ответов — за $y$ .

1. Постройте модель линейной регрессии по методу наименьших квадратов. Для этого используйте матричную формулу NumPy. В качестве ответа укажите полученные оценки коэффициентов модели. Ответ округлите до целого числа.

In [224]:
A = np.column_stack([np.ones((len(data),1)), data.values[:,:-1]])
y = data.values[:,-1]
w_hat = np.linalg.inv(A.T@A)@A.T@y
ans = pd.Series(w_hat,index = data.columns.insert(0,'w_0')[:-1])
ans.round()

w_0       -1232.0
Well          0.0
Por         230.0
Perm        116.0
AI         -365.0
Brittle      25.0
TOC         -78.0
VR          785.0
dtype: float64

#### Задание 5.3
Далее потренируемся строить предсказание для наблюдений целевой переменной.

1. Постройте прогноз выработки газа для скважины с параметрами, указанными ниже. Чему равна абсолютная ошибка построенного вами прогноза для предложенной скважины (в миллионах кубических футов в день). Ответ округлите до целого числа.

![](https://lms.skillfactory.ru/assets/courseware/v1/d8b159aa3b085511221f509dd93e977f/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md2_5_4.png)

mcf/day:

In [233]:
y_new = 4748.315024
x_new =np.array([1,106,15.32,3.71,3.29,55.99,1.35,2.42]) 

y_pred = w_hat@x_new

round(y_new - y_pred)

25

2. Постройте прогноз выработки газа для всех скважин из обучающего набора данных. Чему равно значение метрики MAPE вашей модели? Ответ приведите в процентах (не указывайте знак процента), округлив его до первого знака после точки-разделителя.

In [251]:
from sklearn.metrics import mean_absolute_percentage_error as mape

y_pred = w_hat@A.T

round(mape(y,y_pred)*100,1)

3.6

#### Задание 5.4
Настало время анализа построенной модели. Посмотрите на коэффициенты и сравните их знаки со значениями выборочных корреляций между целевым признаком и факторами, которые вы нашли ранее.


1. Есть ли в вашей модели фактор, при котором коэффициент в модели линейной регрессии противоречит соответствующему коэффициенту корреляции? Например, корреляция говорит, что зависимость между фактором и целью прямая, а модель говорит обратное.

Если такой фактор есть, выберите его название из списка. Если таких факторов несколько, выберите их все:

In [270]:
corr_sign = np.sign(cor_matrix.Prod[:-1])
coeff_signs = np.sign(pd.Series(w_hat[1:],index = data.columns[:-1]))
[i for i,corr_sign,coeff_signs in zip(corr_sign.index,corr_sign,coeff_signs) if corr_sign!=coeff_signs]

['TOC']

#### Задание 5.5
Исключите из данных сильно коррелированные между собой факторы. Под сильной корреляцией в данной задаче будем понимать значения, выше 0.7. Выбирая, какой из коррелированных факторов оставить, руководствуйтесь коэффициентом корреляции с целевой переменной: оставляйте тот фактор, который больше всего коррелирует с объёмом добычи газа.

Также исключите из данных факторы, для которых корреляция с целевой переменной меньше 0.05.

1. Какие факторы вы будете исключать?

In [291]:
to_drop = []

to_drop += list(cor_matrix.Prod.index[cor_matrix.Prod.abs()<0.05])

In [292]:
cor_matrix[cor_matrix.abs()>0.7]

Well       Por      Perm   AI  Brittle       TOC   VR      Prod
Well      1.0       NaN       NaN  NaN      NaN       NaN  NaN       NaN
Por       NaN  1.000000  0.760546  NaN      NaN  0.711831  NaN  0.861910
Perm      NaN  0.760546  1.000000  NaN      NaN       NaN  NaN  0.727426
AI        NaN       NaN       NaN  1.0      NaN       NaN  NaN       NaN
Brittle   NaN       NaN       NaN  NaN      1.0       NaN  NaN       NaN
TOC       NaN  0.711831       NaN  NaN      NaN  1.000000  NaN       NaN
VR        NaN       NaN       NaN  NaN      NaN       NaN  1.0       NaN
Prod      NaN  0.861910  0.727426  NaN      NaN       NaN  NaN  1.000000

In [293]:
cor_matrix.Prod.abs().sort_values(ascending=False)

Prod       1.000000
Por        0.861910
Perm       0.727426
TOC        0.654445
AI         0.390835
VR         0.323182
Brittle    0.237155
Well       0.026817
Name: Prod, dtype: float64

In [294]:
to_drop += ['Perm','TOC']
print(*to_drop)

Well Perm TOC


2. Постройте линейную регрессию на обновлённых после удаления факторов данных по методу наименьших квадратов. Для этого используйте матричную формулу NumPy.

В качестве ответа укажите полученные оценки коэффициентов модели. Ответ округлите до целого числа.

In [319]:
data_proc = data.drop(columns=to_drop)

data_proc.columns

Index(['Por', 'AI', 'Brittle', 'VR', 'Prod'], dtype='object')

In [321]:
A_proc = np.column_stack([np.ones(len(data_proc)),data_proc.values[:,:-1]])
y = data_proc.Prod.values

In [322]:
w_hat_proc = np.linalg.inv(A_proc.T@A_proc)@A_proc.T@y

In [323]:
ans = pd.Series(w_hat_proc,index = data_proc.columns.insert(0,'w_0')[:-1])
ans.round()

w_0       -1835.0
Por         293.0
AI         -200.0
Brittle      28.0
VR          517.0
dtype: float64

3. Сделайте прогноз для всего обучающего набора данных и рассчитайте метрику MAPE (Mean Absolute Percentage Error). Результат приведите в процентах (не указывайте знак процента), округлив его до первого знака после точки-разделителя.

In [334]:
y_pred_proc = w_hat_proc@A_proc.T
mape(y,y_pred_proc)*100

4.044138420436079

4. Удалось ли вам побороть противоречие коэффициентов линейной регрессии и коэффициентов корреляции?

In [332]:
cor_matrix_proc = data_proc.corr()

corr_sign_prov = np.sign(cor_matrix_proc.Prod[:-1])
coeff_signs_proc = np.sign(pd.Series(w_hat_proc[1:],index = data_proc.columns[:-1]))
[i for i,corr_sign,coeff_signs in zip(corr_sign_prov.index,corr_sign_prov,coeff_signs_proc) if corr_sign!=coeff_signs]

[]

### 6. Полиномиальная регрессия
#### Задание 6.1
Построена модель полиномиальной регрессии следующего вида:   
$y=10.4+8 \cdot x_1+0.5 \cdot x_2+3 \cdot x_{1}^{2}+0.4 \cdot x_{2}^{2}+0 \cdot x_1 x_2$

Поступило новое наблюдение, которое характеризуется вектором $x_{new}=(x_{1new}, x_{2new})^T=(1, 4)^T$.

Сделайте прогноз целевой переменной с помощью полученной полиномиальной регрессии. Ответ округлите до первого знака после точки-разделителя.

In [336]:
x1,x2 = 1,4
y = 10.4 + 8*x1 + 0.5*x2 +3*x1**2 + 0.4*x2**2
round(y,1)

29.8

#### Задание 6.4
С помощью классического МНК найдите коэффициенты полиномиальной регрессии, если используется полином второй степени и задан фактор $x$ и целевая переменная $y$.    
$$\vec{y} = w_0 + w_1 \vec{x} + w_2 \vec{x}^2$$  
$$\vec{x}=\left(\begin{array}{c}
1 \\
3 \\
-2 \\
9
\end{array}\right) \vec{y}=\left(\begin{array}{c}
3 \\
7 \\
-5 \\
21
\end{array}\right)$$   

В качестве ответа приведите координаты вектора коэффициентов $\hat{w}_0$, $\hat{w}_1$, $\hat{w}_2$, округлив их до первого знака после точки-разделителя.

In [338]:
A = np.array([[1,1,1,1],[1,3,-2,9],[1,9,4,81]]).T
y = np.array([3,7,-5,21])
np.linalg.inv(A.T@A)@A.T@y

array([ 0.11446013,  2.46095638, -0.01608801])

In [343]:
w0, w1, w2 = (np.linalg.inv(A.T@A)@A.T@y).round(1)
print(w0, w1, w2)

0.1 2.5 -0.0


#### Задание 7.4
Вычислите коэффициенты линейной регрессии с $L_2$ -регуляризацией, используя аналитическую формулу Тихонова, если:

![](https://lms.skillfactory.ru/assets/courseware/v1/26955960b6372607132b2a005abafbc9/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/MATHML_md2_7_10.png)

Коэффициент регуляризации $\alpha=1$.

В качестве ответа приведите значения полученных коэффициентов линейной регрессии, округлив их до второго знака после точки-разделителя.

  нет ответа 
 


In [374]:
x1,x2,x3 = np.array([5,9,4,3,5]), np.array([15,18,18,19,19]), np.array([7,6,7,7,7])
y = np.array([24,22,35,33,36])
alpha = 1
A = np.column_stack([np.ones(len(x1)),x1,x2,x3])
# w_ =np.linalg.inv(A.T@A)@A.T@y
# w_
w_reg = np.linalg.inv(A.T@A + alpha*np.eye((A.T@A).shape[0]))@A.T@y
ans = w_reg.round(2)
print(*ans)

-0.09 -1.71 1.91 0.73


### 8. Практика: полиномиальная регрессия и регуляризация

Продолжим решать задачу от владельца компании «Газ-Таз-Ваз-Нефть» Василия. Исходный датасет представлен здесь.

Ранее, в юните 5, мы смогли построить модель линейной регрессии, которая прогнозирует выработку газа на скважине. Для этого мы с помощью матрицы корреляций и рассуждений отобрали некоррелированные, значимые для предсказания признаки. Далее мы будем использовать именно их (см. задание 5.5).

Мы хотим попробовать улучшить наш результат — метрику MAPE. Для этого воспользуемся моделью полиномиальной регрессии третьей степени. Однако теперь мы знаем, что полиномиальным моделям очень легко переобучиться под исходную выборку, поэтому для контроля качества модели мы будем использовать кросс-валидацию.

Приступим!

#### Задание 8.1
Сгенерируйте полиномиальные признаки третьего порядка на факторах, которые вы выбрали для обучения моделей. Для этого воспользуйтесь генератором полиномов `PolynomialFeatures` из библиотеки `sklearn`. Параметр `include_bias` установите в значение `False`.

In [398]:
from sklearn.preprocessing import PolynomialFeatures

data = pd.read_csv('./Unit_5_data/unconv.csv') 

X = data.drop(columns=['Well','Perm','TOC','Prod'])
y = data.Prod
poly = PolynomialFeatures(degree=3, include_bias=False)
X = poly.fit_transform(X)

1. Сколько факторов у вас получилось после генерации полиномиальных признаков?

In [399]:
X.shape

(200, 34)

Обучите модель линейной регрессии из библиотеки sklearn (LinearRegression) на полученных полиномиальных факторах.

Оцените среднее значение метрики MAPE, используя кросс-валидацию на пяти фолдах.

2. Чему равны средние значения метрики MAPE на тренировочных и валидационных фолдах? Ответ приведите в процентах (не указывайте знак процента), округлив его до первого знака после точки-разделителя.

In [401]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate

lr = LinearRegression()

cv_results = cross_validate(lr, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.1f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.1f} %'.format(-cv_results['test_score'].mean() * 100))	

MAPE на тренировочных фолдах: 1.8 %
MAPE на валидационных фолдах: 2.7 %


#### Задание 8.2
Теперь попробуем воспользоваться линейной регрессией с регуляризацией. Для начала возьмём -регуляризацию.

Обучите модель `Lasso` из библиотеки `sklearn` на полученных полиномиальных факторах, предварительно стандартизировав факторы с помощью `StandardScaler`. Коэффициент регуляризации выставите равным $5$.

Оцените среднее значение метрики `MAPE`, используя кросс-валидацию на пяти фолдах.

Чему равны средние значения метрики `MAPE` на тренировочных и валидационных фолдах? Ответ приведите в процентах (не указывайте знак процента), округлив его до первого знака после точки-разделителя.

In [403]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

In [408]:
data = pd.read_csv('./Unit_5_data/unconv.csv') 

X = data.drop(columns=['Well','Perm','TOC','Prod'])
y = data.Prod

scaler = StandardScaler()
X = scaler.fit_transform(X)

poly = PolynomialFeatures(degree=3, include_bias=False)
X = poly.fit_transform(X)

# lasso = Lasso(alpha=5, fit_intercept=False)
lasso = Lasso(alpha=5, fit_intercept=False, max_iter=5000)
lasso.fit(X, y)

v_results = cross_validate(lasso, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.1f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.1f} %'.format(-cv_results['test_score'].mean() * 100))	

MAPE на тренировочных фолдах: 1.8 %
MAPE на валидационных фолдах: 2.7 %


#### Задание 8.3
Проделаем то же самое с $L_2$-регуляризацией.

Обучите модель `Ridge` из библиотеки `sklearn` на полученных полиномиальных факторах, предварительно стандартизировав факторы с помощью `StandardScaler`. Коэффициент регуляризации выставите равным 1.

Оцените среднее значение метрики `MAPE`, используя кросс-валидацию на пяти фолдах.

Чему равны средние значения метрики `MAPE` на тренировочных и валидационных фолдах? Ответ приведите в процентах (не указывайте знак процента), округлив его до первого знака после точки-разделителя.

In [410]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler

In [411]:
data = pd.read_csv('./Unit_5_data/unconv.csv') 

X = data.drop(columns=['Well','Perm','TOC','Prod'])
y = data.Prod

scaler = StandardScaler()
X = scaler.fit_transform(X)

poly = PolynomialFeatures(degree=3, include_bias=False)
X = poly.fit_transform(X)

# lasso = Lasso(alpha=5, fit_intercept=False)
ridge = Ridge(alpha=5, fit_intercept=False, max_iter=5000)
ridge.fit(X, y)

v_results = cross_validate(ridge, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.1f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.1f} %'.format(-cv_results['test_score'].mean() * 100))	

MAPE на тренировочных фолдах: 1.8 %
MAPE на валидационных фолдах: 2.7 %
