In [3]:
import pandas as pd
import numpy as np

from scipy.optimize import linprog

## Задача о назначениях
У вас есть $\mathbf{n}$ задач и $\textbf{n}$ человек, которые могут их сделать. Каждая задача должна быть сделана одним человеком и каждый должен сделать ровно одну задачу. У человека $\textbf{i}$ задача $\textbf{j}$ будет стоить $\mathbf{с_ij}$. Вам нужно сделать все задачи как можно дешевле.

Решение:

Сформулируем задачу как задачу **ЦЛП**.

Пусть $\mathbf{x_ij} = 1$, если задачу $\textbf{j}$ выполнит человек $\textbf{i}$, а если работы выполнил кто-то другой, то  $\mathbf{x_ij} = 0$.

Минимизируем суммарную стоимость $\mathbf{с_ij} \cdot \mathbf{x_ij}$.

Первое условие: $\mathbf{x_ij}$ либо $0$, либо $1$.  
Второе условие: каждый человек должен взять ровно одну задачу.  
Третье условие: каждую задачу должен взять ровно один человек.

<img src="https://lms.skillfactory.ru/assets/courseware/v1/5798e5ca004d904fe81f53ac188dcd19/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_4_unit_25.png" alt="drawing" width="100"/>

In [4]:
c = [2,3,4,
    1,5,2,
    5,2,3]
A_ub = [[1,1,1,0,0,0,0,0,0],
        [0,0,0,1,1,1,0,0,0],
        [0,0,0,0,0,0,1,1,1]]
b_ub = [1,1,1]
A_eq = [[1,0,0,1,0,0,1,0,0],
        [0,1,0,0,1,0,0,1,0],
        [0,0,1,0,0,1,0,0,1]]
b_eq = [1,1,1]

ans = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=(0,1))
# ans

ans['x'].reshape(3,3)

array([[1.00000000e+00, 1.81638526e-10, 1.50577049e-10],
       [3.34290658e-10, 9.29023527e-11, 1.00000000e+00],
       [2.79748415e-11, 1.00000000e+00, 1.93325148e-10]])

## Задача коммивояжёра
Вам нужно объехать n пунктов, время в пути между пунктами i и j равно dij. Нужно объехать все пункты, чтобы минимизировать суммарное время в пути. В каждый пункт нужно заехать ровно один раз.

Решение:

Сформулируем задачу как задачу ЦЛП. Пусть мы имеем множество отрезков между парами пунктов, и отрезок xij = 1, если в наш путь вошёл отрезок между пунктами i и j, и 0 если не вошёл. Целевая функция — суммарное время проезда.

Первое условие: x либо 0, либо 1.
Второе условие: в каждый пункт нужно въехать ровно один раз.
Третье условие: из каждого пункта нужно выехать ровно один раз.

рис



## Задание 5.1
Составьте оптимальный план перевозок, со Склада № 1 и Склада № 2, в три торговых центра, с учётом тарифов, запасов и потребностей, которые указаны в таблице: 

| Склады|Торговые |центры||
|-|-|-|-|
| |ТЦ1(110шт)|ТЦ2(150шт)|ТЦ3(140)|
|Склад1(180шт)|2|5|3|
|Склад2(220шт)|7|7|6|

Сформулируйте задачу, как задачу линейного программирования, и решите её любым способом (желательно программным).

В ответ запишите минимальную суммарную стоимость поставки (с точностью до целых):

In [5]:
c = [2,5,3,7,7,6]
A_ub = [[1,1,1,0,0,0],
        [0,0,0,1,1,1]]
b_ub = [180,220]
A_eq = [[1,0,0,1,0,0],
        [0,1,0,0,1,0],
        [0,0,1,0,0,1]]
b_eq = [110,150,140]

In [6]:
linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq)

     con: array([4.39231933e-06, 6.01910435e-06, 5.61240813e-06])
     fun: 1899.9999256826393
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([7.20365009e-06, 8.82018173e-06])
  status: 0
 success: True
       x: array([1.09999995e+02, 4.43103329e-08, 6.99999980e+01, 8.98577274e-07,
       1.49999994e+02, 6.99999963e+01])

## Задание 5.2
Решите задачу о назначениях

<img src="https://lms.skillfactory.ru/assets/courseware/v1/304a4fb2612ca0e3c68b1f681bd1876c/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_4_unit_61.png" alt="drawing" width="400"/>
  
  
В ответ запишите минимальную стоимость:



In [7]:
num_tasks, num_workers = 5,5

c = [1000, 12, 10, 19, 8,
    12, 1000, 3, 7, 2,
    10, 3, 1000, 6, 20,
    19, 7, 6, 1000, 4,
    8, 2, 20, 4, 1000]

A_ub,A_eq = [],[]
for i in range(0, num_workers):
    A_ub.append(
        [0]*(num_tasks*i) + [1]*num_tasks + [0]*(num_tasks*(num_workers-i-1))
    )
    A_eq.append(
    ([0]*i + [1] + [0]*(num_workers-i-1)) * num_tasks
    ) 
b_ub = [1]*num_workers
b_eq = [1]*num_tasks

In [8]:
ans = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=(0,1))
ans['fun']

32.00000000034828

In [9]:
ans['x'].reshape(5,5)

array([[3.42156369e-14, 5.00669985e-14, 2.67462223e-01, 8.06720871e-12,
        7.32537777e-01],
       [1.40960989e-12, 2.75234121e-14, 5.01267560e-01, 4.98732440e-01,
        5.14529350e-12],
       [2.67413570e-01, 4.98732440e-01, 3.16811796e-14, 2.33853990e-01,
        2.09335641e-12],
       [7.94701746e-12, 5.01267560e-01, 2.31270216e-01, 3.16749591e-14,
        2.67462223e-01],
       [7.32586430e-01, 5.31310127e-12, 2.08998365e-12, 2.67413570e-01,
        3.03792922e-14]])

## Задание 5.3
Необходимо найти кратчайший маршрут из точки $A$ , который проходит через все другие точки и возвращается в $A$.
![](https://lms.skillfactory.ru/assets/courseware/v1/1dbdee74e890f6f4a8142e80d5799db3/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_4_unit_62.png)

Сформулируйте эту задачу как задачу ЦЛП и решите её.

В ответ запишите длину кратчайшего пути:

In [10]:
import cvxpy
import numpy as np
x = cvxpy.Variable(shape=(5,5), boolean=True)
u = cvxpy.Variable(shape=5, integer=True)

from itertools import product

constraints = [
    cvxpy.sum(x, axis=0) == np.ones(5),
    cvxpy.sum(x, axis=1) == np.ones(5),
    u >= 0,
    u <= 4,
    cvxpy.sum(cvxpy.diag(x)) == 0
]

for i, j in product(range(5), range(5)):
    if i >= 0 and j >= 1 and i != j:
        constraints.append(u[i] - u[j] + 5 * x[i,j] <= 4)

d = np.array([[0, 12, 10, 19, 8], [12, 0, 3, 7, 2], [10, 3, 0, 6, 20], [19, 7, 6, 0, 4], [8, 2, 20, 4, 0]])

func = cvxpy.sum(cvxpy.multiply(x, d))
problem = cvxpy.Problem(cvxpy.Minimize(func), constraints=constraints)
result = problem.solve(solver='ECOS_BB')
np.round(result)

ModuleNotFoundError: No module named 'cvxpy'

# Градиентный спуск
## Задание 7.1
Найдите градиентным спуском минимум функции $2x^2-4xy+y^4+2$
Ответ введите с точностью до целых

In [64]:
def f(x, y):
    return 2*x**2 - 4*x*y + y**4 + 2

def grad_f(x, y):
    dx = 4*x - 4*y
    dy = -4*x + 4*y**3
    return np.array([dx, dy])

def dist(x1, x2):
    return np.sqrt(((x1  - x2)**2).sum())

def grad_desc(f, grad_f, x0, gamma, stop):
    x_cur = x0
    vals = []
    coords = []
    i = 0
    while i<stop:
        x_new = x_cur - gamma * grad_f(*x_cur)
#         x_new = (x_cur[0] - gamma * grad_f(*x_cur)[0],
#                 x_cur[1] - gamma * grad_f(*x_cur)[1])
        if dist(x_new, x_cur) < 1e-9:
            print ('success')
            break
        x_cur = x_new
        vals.append(f(*x_cur))
        coords.append(x_cur)
        i += 1
    #     if i % 100 == 0:
    #         print(f"iter={i}; x=({x_cur[0]:.3f}, {x_cur[1]:.3f});"
    #               f" f(x)={f(*x_cur):.3f}; grad f(x)=({grad_f(*x_cur)[0]:.3f}, {grad_f(*x_cur)[1]:.3f})")
    else: 
        print ('not success')
    return x_cur,f(*x_cur)
   
x0 = np.array([5, 2])
gamma = 1e-3    
grad_desc(f,grad_f,x0,gamma,50000)
# np.around(x_cur), np.around(f(*x_cur))

success


(array([1.00000039, 1.00000016]), 1.0000000000002127)

## Задание 7.2
Обучите линейную регрессию из **Задачи 3.7.3** при помощи градиентного спуска. Чему равно оптимальное значение $L^2-loss?$  

$$L = (2.1 − w_0 − w_1)^2 + (2.9 − w_0 − 3w_1)^2 + (4.1 − w_0 − 5w_1)^2$$  
  
Ответ введите с точностью до целых

In [65]:
def l(w0,w1):
    return (2.1-w0-w1)**2 + (2.9-w0-3*w1)**2 + (4.1-w0-5*w1)**2
    
def grad_l(w0,w1):
    dw0 = 6*w0 + 18*w1 - 18.2
    dw1 = 18*w0 + 70*w1 - 62.6
    return np.array([dw0,dw1])

x0 = np.array([15, 20])
gamma = 1e-3    
ans2 = grad_desc(l,grad_l,x0,gamma,50000)[1]
round(ans2)

success


0

## Задание 7.3
Найдите градиентным спуском минимум функции $x^3-2x^2+y^2+z^2-2xy+xz-yz+3z$

Ответ введите с точностью до целых

In [68]:
def f2(x,y,z):
    return x**3 - 2*x**2 + y**2 +z**2 - 2*x*y + x*z - y*z + 3*z
    
def grad_f2(x,y,z):
    dx = 3*x**2 - 4*x - 2*y + z
    dy = 2*y - 2*x - z
    dz = 2*z + x - y + 3
    return np.array([dx,dy,dz])

x0 = [15, 20,30]
gamma = 1e-3 
stop = 50000

ans3 = grad_desc(f2,grad_f2,x0,gamma,stop)[1]
round(ans3)

success


-7

# Градиентный спуск с momentum

Заметим, что для ускорения спуска было бы неплохо учитывать изменения на прошлом шаге. В примере на рисунке мы видим, как алгоритм колеблется вокруг одной прямой. Было бы здорово явно сказать алгоритму держаться ближе к прямой и двигаться вдоль неё.

![](https://lms.skillfactory.ru/assets/courseware/v1/9adbdb3d799afde8d4061a5686f1b0a7/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_4_unit_44.png)

Решить эту проблему позволяет одна из вариаций градиентного спуска — градиентный спуск с momentum:

![](https://lms.skillfactory.ru/assets/courseware/v1/8ba8de0b76ae23738c6dd678608eb9f9/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_4_unit_42.png)
Идея заключается в том, что на каждой итерации градиентного спуска x изменяется не только на градиент, помноженный на темп обучения, но и на вектор, на который мы передвинулись в прошлом шаге, с некоторым коэффициентом.

В формуле выше: α — это параметр, который будет показывать, насколько сильно будет учитываться прошлый шаг. Для предыдущего примера это работает так: точка начинает двигаться вдоль прямой, которая ведёт к локальному минимуму:


![](https://lms.skillfactory.ru/assets/courseware/v1/3a2239242e607d99ccd0d83e5ca4531d/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_4_unit_45.png)

А значит, алгоритм сходится быстрее. Momentum переводится как импульс, и идея алгоритма отражает идею импульса в физике — пытаемся сымитировать инерцию точки.


## Задание 8.2
Напишите следующую точку градиентного спуска с momentum для функции  
$f(x, y, z)=2x^2-4xz+4y^2-8yz+9z^2+4x+8y-20z$, если текущая точка $– (1, 2, -5)$, перед ней была $(0, 0, 0)$,  
$γ=0.25, α=1$.

Введите координаты точки через запятую (без пробела):

# ====================ПОДВАЛ======================

![таблица](https://lms.skillfactory.ru/assets/courseware/v1/304a4fb2612ca0e3c68b1f681bd1876c/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_4_unit_61.png)